version: '3.8'
services:
    chat-hub-db:
        image: postgres:latest
        container_name: chat-hub-db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: chat-hub-db
        ports:
            - "5432:5432"
        volumes:
            - chat-hub-data:/var/lib/postgresql

volumes:
    chat-hub-data:
